// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotebookMarket.Models;

namespace NotebookMarket.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20200928161450_OrderAdding")]
    partial class OrderAdding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NotebookMarket.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Для навчання"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Ультратонкі"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Геймерські"
                        });
                });

            modelBuilder.Entity("NotebookMarket.Models.Laptop", b =>
                {
                    b.Property<int>("LaptopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LongDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OnDiscount")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LaptopId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Laptops");

                    b.HasData(
                        new
                        {
                            LaptopId = 1,
                            Available = true,
                            CategoryId = 3,
                            ImageUrl = "https://brain.com.ua/static/images/prod_img/3/7/U0371137_big.jpg",
                            LongDescription = "Серія (модельний ряд): L340 Gaming; Тип ноутбуку: Ігровий; Діагональ дисплея: 15.6 FullHD(1920 х 1080) IPS; Процесор 9 - th generation Intel Core i5 9300H(1.6 - 4.1 ГГц); Кількість ядер: 4; Оперативна пам'ять: 8 ГБ; Об'єм SSD: 512 ГБ; No ODD; Відеокарта: NVIDIA GeForce GTX1050; Об'єм вбудованої відеопам'яті: 3 ГБ; Бездротові технології: Bluetooth, Wi - Fi; Інтерфейси та підключення: 1 х USB 2.0, USB 3.2 Type - C, 1 х USB 3.2, HDMI, Комбінований аудіороз'єм; Програмне забезпечення: Windows 10 Home; Особливості: підсвітка клавіатури; Фізичні характеристики: Ширина - 302 мм, Висота - 18 мм, Глибина - 189 мм, Вага - 2.2 кг, Колір - синій.",
                            Model = "НОУТБУК LENOVO IdeaPad L340-15IRH Gaming",
                            OnDiscount = true,
                            Price = 21000m,
                            ShortDescription = "IdeaPad L340 Gaming - ігровий ноутбук,який поєднує в собі портативність і продуктивність для забезпечення кращого досвіду геймінгу у будь - якому місці. "
                        },
                        new
                        {
                            LaptopId = 2,
                            Available = true,
                            CategoryId = 2,
                            ImageUrl = "https://brain.com.ua/static/images/prod_img/7/2/U0465272_big.jpg",
                            LongDescription = "Серія (модельний ряд): ThinkPad; Тип ноутбуку: Ультратонкий; Діагональ дисплея: 13.3 FullHD(1920 х 1080) IPS; Процесор 10 - th generation Intel Core i5 10210U(1.6 - 4.2 ГГц); Кількість ядер: 4; Оперативна пам'ять: 16 ГБ; Об'єм SSD: 512 ГБ; No ODD; Відеокарта: Intel UHD Graphics 620; Об'єм вбудованої відеопам'яті: 2 ГБ; Бездротові технології: Bluetooth, Wi - Fi; Інтерфейси та підключення: 1 х USB 2.0, USB 3.2 Type - C, 1 х USB 3.2, HDMI, Комбінований аудіороз'єм; Програмне забезпечення: Windows 10 Home; Особливості: підсвітка клавіатури;Фізичні характеристики: Ширина - 302 мм, Висота - 18 мм, Глибина - 189 мм, Вага - 1.25 кг, Колір - чорний.",
                            Model = "НОУТБУК LENOVO THINKPAD X13 YOGA",
                            OnDiscount = true,
                            Price = 60300m,
                            ShortDescription = "Надійність, потужність, мультирежимність притаманні Lenovo ThinkPad X13 YOGA "
                        },
                        new
                        {
                            LaptopId = 3,
                            Available = true,
                            CategoryId = 1,
                            ImageUrl = "https://brain.com.ua/static/images/prod_img/4/4/U0443644_big.jpg",
                            LongDescription = "Серія (модельний ряд): ASUS Zenbook; Тип ноутбуку: Бізнеc; Діагональ дисплея: 13.3 FullHD(1920 х 1080) IPS; Процесор 10 - th generation Intel Core i5 10210U(1.6 - 4.2 ГГц); Кількість ядер: 4; Оперативна пам'ять: 8 ГБ; Об'єм SSD: 512 ГБ; No ODD; Відеокарта: NVIDIA GeForce MX250; Об'єм вбудованої відеопам'яті: 2 ГБ; Бездротові технології: Bluetooth, Wi - Fi; Інтерфейси та підключення: 1 х USB 2.0, USB 3.2 Type - C, 1 х USB 3.2, HDMI, Комбінований аудіороз'єм; Програмне забезпечення: Windows 10 Home; Особливості: підсвітка клавіатури;Фізичні характеристики: Ширина - 302 мм, Висота - 18 мм, Глибина - 189 мм, Вага - 1.19 кг, Колір - синій.",
                            Model = "НОУТБУК ASUS ZENBOOK UX334FLC-A3108T",
                            OnDiscount = true,
                            Price = 30999m,
                            ShortDescription = "Asus ZenBook UX334FLC – неперевершена краса, яка закута у корпус з фантастичною обробкою."
                        });
                });

            modelBuilder.Entity("NotebookMarket.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("OrderPlaced")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OrderTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("NotebookMarket.Models.OrderDetails", b =>
                {
                    b.Property<int>("OrderDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("LaptopId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("PieId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderDetailsId");

                    b.HasIndex("LaptopId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("NotebookMarket.Models.ShoppingCartItem", b =>
                {
                    b.Property<int>("ShoppingCartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("LaptopId")
                        .HasColumnType("int");

                    b.Property<string>("ShoppingCartId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShoppingCartItemId");

                    b.HasIndex("LaptopId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("NotebookMarket.Models.Laptop", b =>
                {
                    b.HasOne("NotebookMarket.Models.Category", "Category")
                        .WithMany("Laptops")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NotebookMarket.Models.OrderDetails", b =>
                {
                    b.HasOne("NotebookMarket.Models.Laptop", "Laptop")
                        .WithMany()
                        .HasForeignKey("LaptopId");

                    b.HasOne("NotebookMarket.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NotebookMarket.Models.ShoppingCartItem", b =>
                {
                    b.HasOne("NotebookMarket.Models.Laptop", "Laptop")
                        .WithMany()
                        .HasForeignKey("LaptopId");
                });
#pragma warning restore 612, 618
        }
    }
}
